version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  postgres-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
